### ISSUE TITLE
Equality behaviour of Nans

### ISSUE THREAD

**Issue by Joshcarp** [anz-bank/decimal#19]
the IEEE 754-r specifies that:
"Four mutually exclusive relations are possible: less than, equal, greater than, and unordered. The last case
arises when at least one operand is NaN. Every NaN shall compare unordered with everything, including
itself"

which means that Nan != Nan 
although there isn't a way to set equality behaviour in golang (that i know of), but it's got to do with the bits that make up the Nan

**Comment by anzdaddy** [comment]
The only real option for a library is to define something like `Eq`, `Lt` and `Gt` and require their use instead of `==` et al.

**Comment by Joshcarp** [comment]
Fixed in bc488e69d
