### ISSUE TITLE
Tighten up rounding logic

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/decimal#28]
Currently, rounding status is one of `eq0`, `lt5`, `eq5` and `gt5`. Tests then look for different combinations of these. For instance, `round()` has the following test:

```go
if context.rndStatus == gt5 || context.rndStatus == eq5 {
```

This could be made more efficient if the constants were intialised with `1 << iota`. You could then test:

```go
if context.rndStatus & (gt5 | eq5) != 0 {
```

**Comment by Joshcarp** [comment]
Dunno how this might work with 	
`if (rndStatus == eq5 && significand%2 == 1) || rndStatus == gt5 {`

**Comment by anzdaddy** [comment]
Leave it as is, this is a very minor optimisation.
